<?php
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function add_article_success_message_form_alter(&$form, FormStateInterface $form_state, $form_id) 
{
    if ($form_id == 'node_article_form') 
	{
		$form['actions']['publish']['#submit'][] = 'add_article_success_message_form_submit';
    } 
}

/**
 * Add the custom message on "Save and publish".
 */
function add_article_success_message_form_submit(array &$form, FormStateInterface $form_state)
{
    drupal_set_message(t("Go ahead and check if you haven't made any mistake."),'status');
}